// Generated by CoffeeScript 1.9.3
var Agenda, agenda, collection_form, db, mongojs;

Agenda = require('agenda');

mongojs = require('mongojs');

agenda = new Agenda({
  db: {
    address: 'localhost/projek',
    collection: 'agenda'
  }
});

db = mongojs('127.0.0.1/projek');

collection_form = "formpage";

db.collection(collection_form).find({}, function(error, result) {
  result.forEach(function(item) {
    console.dir(item);
    agenda.define(item.name, function(job, done) {
      console.dir(item.query);
      return done();
    });
    return agenda.schedule(item.customType, item.name);
  });
  return agenda.start();
});

console.log('Wait');
