// Generated by CoffeeScript 1.9.3
var Agenda, agenda, dbProjek, dbSetipe, mongojs;

Agenda = require('agenda');

mongojs = require('mongojs');

agenda = new Agenda({
  db: {
    address: 'localhost/projek',
    collection: 'agenda'
  }
});

dbProjek = mongojs('127.0.0.1/projek', ['formpage']);

dbSetipe = mongojs('127.0.0.1/setipe', ['user']);

dbProjek.formpage.find({}, function(error, result) {
  result.forEach(function(item) {
    console.dir(item);
    agenda.define(item.name, function(job, done) {
      var query;
      query = JSON.parse(item.query);
      console.dir("Query = " + query);
      dbSetipe.user.find({
        query: query
      }, function(error2, result2) {
        return console.dir(result2);
      });
      console.log("Test 2");
      return done();
    });
    return agenda.schedule(item.customType, item.name);
  });
  return agenda.start();
});

console.log('Wait');
